### ISSUE TITLE
Write to database throws buffer.writeUInt32LE is not a function 6.30

### ISSUE THREAD

**Issue by mgarf** [tediousjs/tedious#954]
Update:

Kept downgrading versions till it worked. Last working version 6.1.2. First broken version is 6.2.0

-----

Partial Stack Trace:

 ```
 TypeError: buffer.writeUInt32LE is not a function
      at Object.writeParameterData (C:\Users\REMOVED\REMOVED\Documents\REMOVED\node_modules\tedious\lib\data-types\nvarchar.js:65:14)
      at RpcRequestPayload._writeParameterData (C:\Users\REMOVED\REMOVED\Documents\REMOVED\node_modules\tedious\lib\rpcrequest-payload.js:107:10)
      at writeNext (C:\Users\REMOVED\REMOVED\Documents\REMOVED\node_modules\tedious\lib\rpcrequest-payload.js:53:12)
      at RpcRequestPayload.getData (C:\Users\REMOVED\REMOVED\Documents\REMOVED\node_modules\tedious\lib\rpcrequest-payload.js:60:5)
      at Connection.makeRequest (C:\Users\REMOVED\REMOVED\Documents\REMOVED\node_modules\tedious\lib\connection.js:1798:17)
      at Connection.execSql (C:\Users\REMOVED\REMOVED\Documents\REMOVED\node_modules\tedious\lib\connection.js:1507:10)
```

This code was working on 5.0.3 then i upgraded up to 6.3 and encountered this...

Here is the code that causes the stack trace:

```
var request = new Request("select Id FROM dbo." + process.env['DB_TABLE'] + " WHERE messageId = @messageId", function(err, rowCount) {
    if (err) reject(err);

    this.context.log('Check for Existing Record returned: ' + rowCount);
    resolve(rowCount);
}.bind(this));

request.addParameter('messageId', TYPES.VarChar, messageId);
this.connection.execSql(request);
```

Parameters logged out before it hits the function that calls that buffer function

```
[ { type:
     { id: 231,
       type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function: declaration],
       resolveLength: [Function: resolveLength],
       writeTypeInfo: [Function: writeTypeInfo],
       writeParameterData: [Function: writeParameterData],
       validate: [Function: validate] },
    name: 'statement',
    value:
     'select Id FROM dbo.inboundStaging WHERE messageId = @messageId',
    output: false,
    length: undefined,
    precision: undefined,
    scale: undefined },
  { type:
     { id: 231,
       type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function: declaration],
       resolveLength: [Function: resolveLength],
       writeTypeInfo: [Function: writeTypeInfo],
       writeParameterData: [Function: writeParameterData],
       validate: [Function: validate] },
    name: 'params',
    value: '@messageId nvarchar(82)',
    output: false,
    length: undefined,
    precision: undefined,
    scale: undefined },
  { type:
     { id: 231,
       type: 'NVARCHAR',
       name: 'NVarChar',
       hasCollation: true,
       dataLengthLength: 2,
       maximumLength: 4000,
       declaration: [Function: declaration],
       resolveLength: [Function: resolveLength],
       writeTypeInfo: [Function: writeTypeInfo],
       writeParameterData: [Function: writeParameterData],
       validate: [Function: validate] },
    name: 'messageId',
    value:
     '<BL0PR4R18MB22269432BD89616EF946F171BDA60@BL0PR18MB2226.namprd18.prod.outlook.com>',
    output: false,
    length: undefined,
    precision: undefined,
    scale: undefined } ]
```

**Comment by IanChokS** [comment]
@mgarf, there has a behavior change introduced on Tedious side for the writeparameterdata function which include an extra parameter called 'cb', and the behavior on the tedious-connection-pool side has not been changed for the function call, so this will cause issue. the fix is just add a empty call back function for the function call on tedious-connection-pool. Hopefully this fixes your issue?

**Comment by MichaelSun90** [comment]
Hi @mgarf,  it has been a few days. Just wondering, is this still an issue on your side?

**Comment by mgarf** [comment]
Hi sorry been buried, i'm not using the tedious connection pool

**Comment by MichaelSun90** [comment]
Hi @mgarf, I have tried a similar scenario on my local set up with the lastest Tedious release. It seems to work fine on my side. Do you mind to provide a runnable test script, so I can try to reproduce the issue? 
I will also put mine here, so you can try to run this on your side, see if ther behavior is the same: 

`Connection = require('tedious').Connection,
	Request = require('tedious').Request,
	TYPES = require('tedious').TYPES;

var config = {
  server: 'localhost',
  authentication: {
    type: 'default',
    options: {
      userName: "*****",
      password: "*****",
    }
  }
};

var connection = new Connection(config);

connection.on('connect', function(err) {
  var request = new Request("select * from MyTable WHERE messageId = @messageId",
	function(err){
		if(err){
			console.log(err);
		};
	});

  request.addParameter('messageId', TYPES.VarChar, 'ABCD');
  connection.execSql(request);
  request.on('row', function(columns) {
    columns.forEach(function(column) {
      if (column.value === null) {
        console.log('NULL');
      } else {
        console.log(column.value);
      }
    });
  });
}
);

connection.on('debug', function(text) {
    console.log(text);
  }
);`

**Comment by mgarf** [comment]
hmm, alright let me work on a test script to provide

**Comment by MichaelSun90** [comment]
Thanks, you can also try my script as well.

**Comment by IanChokS** [comment]
Hi @mgarf, just wondering if you were able to solve this issue?

**Comment by mgarf** [comment]
this turned out a issue with my code, my apologies
